### ISSUE TITLE
Twitch API Helix

### ISSUE THREAD

**Issue by spesvictus-zz** [thedist/Twitch_API_v5#5]
Will this module be maintained for new Twitch API?

**Comment by thedist** [comment]
With Helix being a completely new API, and Kraken being deprecated, I think rather than try to integrate Helix into this module and have to rename the module and everything, I plan to maintain this module for Kraken and create a separate module for Helix.

Right now though Helix is still severely lacking key endpoints from Kraken, webhooks aren't implemented yet, and a lot of documentation is lacking, so I'm holding off creating a new module dedicated to Helix until there is sufficient need/demand. For those looking to play around with Helix right away before most of the features are there it is easy enough to just use the request module to do it.
